import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    "intro",
    {
      type: "category",
      label: "Produkt",
      collapsed: false,
      items: [
        "product/vision",
        "product/roadmap",
        "product/user-stories",
      ],
    },
    {
      type: "category",
      label: "Design",
      collapsed: false,
      items: [
        "design/claude-design-exports",
        "design/design-system",
        "design/prototypes",
      ],
    },
    {
      type: "category",
      label: "Architektur",
      collapsed: false,
      items: [
        "architecture/overview",
        {
          type: "category",
          label: "Architecture Decision Records",
          collapsed: true,
          items: [{ type: "autogenerated", dirName: "architecture/decisions" }],
        },
      ],
    },
    {
      type: "category",
      label: "API",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    {
      type: "category",
      label: "Runbooks",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "runbooks" }],
    },
  ],
};

export default sidebars;
